Docs
athenarc/EOSCF-ContentBasedRS pull request #1
Opened 2023-10-23 09:38 UTC by MikeXydas

2023-10-23 14:19 UTC, AnnaMitsopoulou requested changes

2023-10-23 14:19 UTC, AnnaMitsopoulou commented on docs/assets/similar_services_architecture.png
- reverse arrows in rs mongo and argo monitoring. (We read from the dbs, we do not write)
- add similar services component to service recommender, which uses the Similar Services Retriever

2023-10-23 15:54 UTC, MikeXydas commented on docs/assets/similar_services_architecture.png
![diagram-export-10-23-2023-6_51_17-PM](https://github.com/athenarc/EOSCF-ContentBasedRS/assets/35707606/1ada1542-e8b7-44c3-a757-767426eed782)

@AnnaMitsopoulou Like that?

2023-10-23 16:02 UTC, AnnaMitsopoulou commented on docs/assets/similar_services_architecture.png
yes

2023-11-07 08:06 UTC, AnnaMitsopoulou approved these changes

2023-11-07 08:06 UTC, merged